name: Frontend
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Test Report
        uses: mridang/action-test-reporter@v1.3.0
